version: '3.4'

services:
    db-app:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        restart: always
        environment: 
            - SA_PASSWORD=P@ssw0rd
            - ACCEPT_EULA=Y
        ports: 
            - "1433:1433"
        volumes:
            - db-data:/var/opt/mssql/data
            - log:/var/opt/mssql/log
            - secrets:/var/opt/mssql/secrets

    app: 
      image: lista-tarefas
      restart: always
      build:
        dockerfile: Dockerfile
      ports:
        - "5000:80"

volumes:
    db-data:
    log:
    secrets: